---
# tasks file for mapred_job_tracker
- name: Copy files on job tracker
  copy:
    src: "{{ item }}"
    dest: "/root/"
  loop:
          - jdk-8u171-linux-x64.rpm
          - hadoop-1.2.1-1.x86_64.rpm
  register: files
- debug:
        var: files

- name: Install java on job tracker
  shell: "rpm -ivh jdk-8u171-linux-x64.rpm"
  register: java
- debug:
        var: java

- name: Install Hadoop on job tracker
  shell: "rpm -ivh hadoop-1.2.1-1.x86_64.rpm --force"
  register: hadoop
- debug:
        var: hadoop
- name: Configuring mapred-site.xml file
  blockinfile:
    path: /etc/hadoop/mapred-site.xml
    insertafter: "<configuration>"
    block:
            <property>
            <name>mapred.job.tracker</name>
            <value>{{ jtip }}:{{ port_no }}</value>
            </property>
  register: site_file
- debug:
        var: site_file

- name: Start Namenode
  shell: "hadoop-daemon.sh start jobtracker"
  register: status_jt
- debug:
        var: status_jt

- name: Checking jobtracker service
  shell: "jps"
  register: jps
- debug:
        var: jps.stdout_lines

